## Global Historical Climatology Network Dataset
Variables are stored in both rows and columns
This dataset represents the daily weather records for a weather station (MX17004) in Mexico for five months in 2010.

In [451]:
import numpy as np
import pandas as pd

df = pd.read_csv("../weather-raw.csv")

In [479]:
dff = df.fillna(0)
dff

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,tmax,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.8,0.0
1,MX17004,2010,1,tmin,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.5,0.0
2,MX17004,2010,2,tmax,0.0,27.3,24.1,0.0,0.0,0.0,...,0.0,29.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,MX17004,2010,2,tmin,0.0,14.4,14.4,0.0,0.0,0.0,...,0.0,10.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,MX17004,2010,3,tmax,0.0,0.0,0.0,0.0,32.1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,MX17004,2010,3,tmin,0.0,0.0,0.0,0.0,14.2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,MX17004,2010,4,tmax,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,36.3,0.0,0.0,0.0,0.0
7,MX17004,2010,4,tmin,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,16.7,0.0,0.0,0.0,0.0
8,MX17004,2010,5,tmax,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,33.2,0.0,0.0,0.0,0.0
9,MX17004,2010,5,tmin,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,18.2,0.0,0.0,0.0,0.0
10,MX17004,2010,6,tmax,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.1,0.0,0.0
11,MX17004,2010,6,tmin,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,0.0,0.0
12,MX17004,2010,7,tmax,0.0,0.0,28.6,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,MX17004,2010,7,tmin,0.0,0.0,17.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,MX17004,2010,8,tmax,0.0,0.0,0.0,0.0,29.6,0.0,...,0.0,26.4,0.0,29.7,0.0,0.0,0.0,28.0,0.0,25.4
15,MX17004,2010,8,tmin,0.0,0.0,0.0,0.0,15.8,0.0,...,0.0,15.0,0.0,15.6,0.0,0.0,0.0,15.3,0.0,15.4
16,MX17004,2010,10,tmax,0.0,0.0,0.0,0.0,27.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,31.2,0.0,0.0,0.0
17,MX17004,2010,10,tmin,0.0,0.0,0.0,0.0,14.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0
18,MX17004,2010,11,tmax,0.0,31.3,0.0,27.2,26.3,0.0,...,0.0,0.0,0.0,0.0,28.1,27.7,0.0,0.0,0.0,0.0
19,MX17004,2010,11,tmin,0.0,16.3,0.0,12.0,7.9,0.0,...,0.0,0.0,0.0,0.0,12.1,14.2,0.0,0.0,0.0,0.0
20,MX17004,2010,12,tmax,29.9,0.0,0.0,0.0,0.0,27.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,MX17004,2010,12,tmin,13.8,0.0,0.0,0.0,0.0,10.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [453]:
grouped = dff.groupby("month").sum()
grouped.head()

,year,d1,d2,d3,d4,d5,d6,d7,d8,d9,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
month,,,,,,,,,,,,,,,,,,,,,
1,4020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.3,0.0
2,4020,0.0,41.7,38.5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,40.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4020,0.0,0.0,0.0,0.0,46.3,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,53.0,0.0,0.0,0.0,0.0
5,4020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,51.4,0.0,0.0,0.0,0.0

In [454]:

cut_df = df[df.columns[4:35]]
df_sum = cut_df.sum()
df_count = cut_df.count(axis=0)
df_mean = df_sum/df_count
print("media diaria durante todos los meses")
print(df_mean)

media diaria durante todos los meses
d1     21.850000
d2     22.325000
d3     21.150000
d4     19.600000
d5     20.862500
d6     19.150000
d7     20.500000
d8     23.150000
d9           NaN
d10    25.650000
d11    21.550000
d12          NaN
d13    23.150000
d14    22.225000
d15    19.600000
d16    24.350000
d17    22.750000
d18          NaN
d19          NaN
d20          NaN
d21          NaN
d22          NaN
d23    20.500000
d24          NaN
d25    22.650000
d26    20.100000
d27    24.383333
d28    23.100000
d29    22.850000
d30    21.150000
d31    20.400000
dtype: float64

In [478]:
month = grouped.T[1:32]
month_sum = month.sum()
month = month.replace(0.0, np.nan)
month_count = month.notnull().sum()
month_mean = month_sum/month_count
#print("media mensual: ",month_mean)


month = dff.T
month =  month[4:35]
display(month)
month_sum = month.sum()
month = month.replace(0.0, np.nan)
month_count = month.notnull().sum()

final_count = []
final_sum = []
for i in range(0,22,2):
    print(i)
    final_count.append(month_count[i]+month_count[i+1])
    final_sum.append(month_sum[i]+month_sum[i+1])

result=[]
for i in range(len(final_sum)):
    result.append(final_sum[i]/final_count[i])

print("media mensual:")
for r in range(len(result)):
    print("\nMonth",r+1)
    print(result[r])

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
d1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,29.9,13.8
d2,0,0,27.3,14.4,0,0,0,0,0,0,...,0,0,0,0,0,0,31.3,16.3,0,0
d3,0,0,24.1,14.4,0,0,0,0,0,0,...,28.6,17.5,0,0,0,0,0,0,0,0
d4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,27.2,12,0,0
d5,0,0,0,0,32.1,14.2,0,0,0,0,...,0,0,29.6,15.8,27,14,26.3,7.9,0,0
d6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,27.8,10.5
d7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,28.1,12.9,0,0,0,0
d8,0,0,0,0,0,0,0,0,0,0,...,0,0,29,17.3,0,0,0,0,0,0
d9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d10,0,0,0,0,34.5,16.8,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d11,0,0,29.7,13.4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d13,0,0,0,0,0,0,0,0,0,0,...,0,0,29.8,16.5,0,0,0,0,0,0
d14,0,0,0,0,0,0,0,0,0,0,...,29.9,16.5,0,0,29.5,13,0,0,0,0
d15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,28.7,10.5,0,0,0,0
d16,0,0,0,0,31.1,17.6,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d23,0,0,29.9,10.7,0,0,0,0,0,0,...,0,0,26.4,15,0,0,0,0,0,0
d24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d25,0,0,0,0,0,0,0,0,0,0,...,0,0,29.7,15.6,0,0,0,0,0,0
d26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,28.1,12.1,0,0
d27,0,0,0,0,0,0,36.3,16.7,33.2,18.2,...,0,0,0,0,0,0,27.7,14.2,0,0
d28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,31.2,15,0,0,0,0
d29,0,0,0,0,0,0,0,0,0,0,...,0,0,28,15.3,0,0,0,0,0,0
d30,27.8,14.5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
d31,0,0,0,0,0,0,0,0,0,0,...,0,0,25.4,15.4,0,0,0,0,0,0

0
2
4
6
8
10
12
14
16
18
20
media mensual:

Month 1
21.15

Month 2
20.4875

Month 3
24.38333333333333

Month 4
26.5

Month 5
25.700000000000003

Month 6
23.4

Month 7
23.125

Month 8
22.057142857142857

Month 9
20.990000000000002

Month 10
20.31

Month 11
20.5